feat: topItemCount for TableVirtuoso
petyosi/react-virtuoso pull request #1147
Opened 2024-10-13 08:28 UTC by yuta4j1

Resolves #1130 .
I wanted to separate topItems from items as in `Virtuoso.tsx`, but in the case of `TableVirtsuoso.tsx`, the Items component contains a TableBodyComponent, so I could not put a TableRowComponent outside of it, and So, this is how it is implemented.
If you have any ideas for a better implementation, I'd be happy to point them out.

2024-10-14 05:55 UTC, petyosi requested changes

2024-10-14 05:55 UTC, petyosi commented on src/TableVirtuoso.tsx
> +  const topItems = (showTopList ? listState.topItems : []).map((item) => {
This is duplicating the `const items` block below. I would rather have this refactored into a common routine to reduce size and avoid potential bugs because things changed in one of the blocks but were forgotten into the other.

2024-10-14 05:55 UTC, petyosi commented on src/TableVirtuoso.tsx
> +    const offsetTop = listState.topItems.reduce((acc, item, itemIndex) => {
This nested loop can theoretically cause performance problems.

2024-10-14 13:48 UTC, petyosi commented
Looks good, I will test and merge if everything is ok.

2024-10-14 13:53 UTC, yuta4j1 commented on src/TableVirtuoso.tsx
> +  const topItems = (showTopList ? listState.topItems : []).map((item) => {
I made topItems and items common. Does it match your image?
78bd0c6bba33d98b33a48325560b4de48883a436

2024-10-14 13:53 UTC, yuta4j1 commented on src/TableVirtuoso.tsx
> +    const offsetTop = listState.topItems.reduce((acc, item, itemIndex) => {
Indeed. I made a list of offsets in advance and used them in the loop.
https://github.com/petyosi/react-virtuoso/pull/1147/files#diff-bbd02b2ee6e5b3189b3c2bcbed9062a411c4ad1a500e9e8fd47777a5a65d25b5R93-R100

2024-10-15 05:10 UTC, merged

2024-10-15 05:10 UTC, petyosi commented
@yuta4j1 Thank you for your contribution :).